### PR TITLE
Added: windows use

### PR DESCRIPTION
**Pull request by JanGalek**
Added: windows use

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you!

Do you have any idea how to write every OS-compatible paths to scripts?

**Comment by JanGalek** [comment]
You can test platform (win32 - Windows 32/64 bit, linux, OSX)

I dont know path in OSX (maybe like Linux ? :) ), so I tested only windows.

`
        var run = (process.platform === 'win32') ? 'vendor\\bin\\statie' : 'vendor/bin/statie';
        exec(run + ' generate', function (err, stdout, stderr) {
            console.log(stdout);
            console.log(stderr);
        });
`

**Comment by TomasVotruba** [comment]
That looks like great analysis. Thanks.

`path` seems the best here. I will try it.

**Comment by JanGalek** [comment]
Maybe you find better way, https://nodejs.org/api/path.html

**Pull request merged**
