### PR TITLE
Patch: use minetro/doctrine-extensions instead of rixxi

### PR DESCRIPTION
**Pull request by f3l1x**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for reminding yourself! 

Happy to merge

**Comment by f3l1x** [comment]
You're welcome. Level 10th of self-promoting reached today. :rofl:

**Comment by TomasVotruba** [comment]
Congrats! What other actions did you take? 

PR post is the best :)

**Comment by TomasVotruba** [comment]
...and done on packagist as well

image

**Pull request merged**
