### PR TITLE
Remove unnecessary word

### PR DESCRIPTION
**Pull request by maccath**
A program cannot be sexy. Secretaries are not always female or sexy. The best secretaries are not good because they are sexy.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Good point :)

**Comment by maccath** [comment]
Thank you for merging this, I appreciate it! 🙇‍♀️

**Comment by TomasVotruba** [comment]
I'm glad you took the time and explained to me :+1: I didn't really though about this before

**Comment by TomasVotruba** [comment]
If you find anything like this on my blog, just send PR. It's welcomed :bowing_man:

**Pull request merged**
