### PR TITLE
case sensitive ?

### PR DESCRIPTION
**Pull request by harikt**
Changed from `packages/Lekarna/Filesystem` to `packages/lekarna/filesystem`

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hi, why this change?

**Comment by harikt** [comment]
Hey @TomasVotruba ,

May be you are using Windows ? 

If you have created the files in `packages/lekarna/filesystem` then the path should be smaller, else you want to make it upper case. The only thing I am pointing here is this will not work in *nix systems if you are using different cases.

**Comment by TomasVotruba** [comment]
Oh, I see now after reading the post. The directory name is already lowercase.

In that way it's ok

**Comment by TomasVotruba** [comment]
Thank you

**Pull request merged**
