### PR TITLE
[blog] symbiotic controller init

### PR DESCRIPTION
**Pull request by TomasVotruba**
## Intro For

- [SymbioticController](https://github.com/Symplify/SymbioticController)

## Preview

symbiotic controller nette nbsp presenter nbsp with nbsp freedom tomas votruba

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Hey @lexi, I've prepared intro post for `SymbioticController`. As you're an experienced user and great source of my helpful feedback for this, could I ask you for review of the post?

Thanks and see you soon :)

**Comment by TomasVotruba** [comment]
Hey @lexinek, I've prepared intro post for `SymbioticController`. As you're an experienced user and great source of my helpful feedback for this, could I ask you for review of the post?

Thanks and see you soon :)

**Comment by Lexinek** [comment]
@TomasVotruba you can expect my feedback in the morning. See you later today ;).

**Comment by Lexinek** [comment]
Hi i found some typos (found many more but most of them were missing `a` or `an`, these are most obvious): 

Self explaining screenshot 2017-06-20 08 45 32

Im not sure, but i think `event` should be `even`?
screenshot 2017-06-20 08 46 06

`frontent` -> `frontend`
screenshot 2017-06-20 08 48 02

`year` -> `years`
screenshot 2017-06-20 08 48 41

`and` -> `an`
screenshot 2017-06-20 08 48 53

It should be changed either to `seemed weird to me` or `seemed to be weird to me`
screenshot 2017-06-20 08 49 42

Ok, that were typos, now something constructive :-)

Actually the title is `HOW`, i expected this answer `HOW` to be answered, instead you are offering answers `WHY`. I was not able to click to these links (from jpeg :-) ) maybe answers are there, but i would expect to not jump from `HOW` to `WHY` without explaining it.
screenshot 2017-06-20 08 51 19

There are 2 images, that would be awesome, if could be replaced with GIFs, demonstrating how useful this is -> 1st show me how "hard" it is with nette route to find a presenter and then show it with class routes.
WIth templates it will be a bit harder, because i have no idea how to demonstrate how to find template associated with a presenter, as it is handled by magic in background (UI\Presenter) and you have no chance to do it. It would be as well nice to mention and as opposite as a bonus gif how easy it is with invokable presenters.
screenshot 2017-06-20 08 55 19

**Comment by TomasVotruba** [comment]
**Thanks for extensive report!** I will check it tomorrow.

Just curious: do you prefer such manual report over [sending commit with fixes to this PR](https://github.com/TomasVotruba/tomasvotruba.cz/edit/single-action-presenter/source/_posts/2017/2017-06-15-symbiotic-controller-nette-presenter-with-freedom.md?pr=/TomasVotruba/tomasvotruba.cz/pull/111)?

**Comment by Lexinek** [comment]
Yeah, i feel more confident when writing "feedback". If i send PR, i would feel more responsible for that code/PR overall. Like this it is much nicer as you can take anything from my feedback, that you consider to be useful, possibly nothing ofc :-).

**Comment by TomasVotruba** [comment]
@Lexinek I see. Thanks for both explaining in person and writing it down here.

I'm on it :+1:

**Comment by TomasVotruba** [comment]
Typos :heavy_check_mark: 

HOW/WHY, good point. There sources are to get more inspiration and background for the decoupling process itself.
I've changed that to: *Inspiration from Symfony Community - Matthias Noback & Keving Dunglas*

What do you think?

**Comment by TomasVotruba** [comment]
@Lexinek It's been published here: https://www.tomasvotruba.cz/blog/2017/06/19/symbiotic-controller-nette-presenter-with-freedom

Feel free to comment and check those gifs

**Pull request merged**
