### PR TITLE
Add PHP 7.3 test

### PR DESCRIPTION
**Pull request by TomasVotruba**
To cover #438

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Waits on https://github.com/travis-ci/travis-ci/issues/9717

**Comment by TomasVotruba** [comment]
New blocker PHP CS Fixer: https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4051

**Comment by TomasVotruba** [comment]
@localheinz btw, any ideas how to solve PHP CS Blocker?

**Comment by localheinz** [comment]
@TomasVotruba 

How about 

* removing `friendsofphp/php-cs-fixer` from `composer.json` on PHP 7.3
* requiring `friendsofphp/php-cs-fixer` on PHP 7.2 only

?

**Comment by TomasVotruba** [comment]
@localheinz That could work at least here. Thanks :+1: 

Well, what if need to test code that depends on `friendsofphp/php-cs-fixer` on PHP 7.3?

**Comment by TomasVotruba** [comment]
> removing friendsofphp/php-cs-fixer from composer.json on PHP 7.3

I'm trying this now, but got stuck. How can I remove that from a 3rd party dependency?

**Comment by TomasVotruba** [comment]
Waits on cascade of 3rd party packages upgrade, might take a long time. 
Closing for now

**Pull request closed without merging**
