### PR TITLE
Update 2018-06-21-open-source-is-selfish.md

### PR DESCRIPTION
**Pull request by dakur**
;-)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the contribution

Could you also add some nice source as link to that date? So there won't be another PR changing is to another number without reasioning

**Comment by TomasVotruba** [comment]
I rather connect with the year of new state.

Do you think you'll be sending this PR if it would?
Also, these events are usually know to people in the state where it happened. The younger, the less

**Comment by dakur** [comment]
> Do you think you'll be sending this PR if it would?

I don't understand.

However, it does not hurt me, so if you prefer 1993, it's your choice. ;-)

**Comment by TomasVotruba** [comment]
> Do you think you'll be sending this PR if it would?

I mean if there would a source, it would give a backup to that statement.

Why did you close it? I just wanted to add a link to it.

**Comment by dakur** [comment]
Because I did not understand what do you mean and I did not want to spend time on one "word" which is not the point of that article at all. :-)

**Comment by TomasVotruba** [comment]
I see.

I'm sorry I did not explain in more clear way.

**Pull request closed without merging**
