### PR TITLE
add safe post

### LINKED ISSUE #653: [post] My experience with "safe"
Ref https://github.com/Symplify/Symplify/pull/1409#issuecomment-460998763

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #653 

There you go @akondas :)

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@akondas Could I ask you to speed-review? Just for main fuckups

**Comment by akondas** [comment]
No problem :+1:

**Comment by TomasVotruba** [comment]
Let's :ship: it

**Comment by akondas** [comment]
I have not read yet :(

**Comment by TomasVotruba** [comment]
> No problem :+1: 

I though you did :D 

Feel free to read now, I'll integrate notes of course.

**Comment by akondas** [comment]
Looks great, retweeted, thanks :+1:

**Comment by TomasVotruba** [comment]
Your great title convinced me :)

**Pull request merged**
