### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by B-Galati**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This is not a typo, the experiment was really with 2 package.
I always try to make experiments as small as they can be, so I can have results for the least energy.

**Comment by B-Galati** [comment]
Thanks!
I still don't get it. Why talking about 20 commits in 20 packages? That's just a random number that does not match your experiment?

**Comment by TomasVotruba** [comment]
Oh, I see the other numbers are typo :)

**Comment by TomasVotruba** [comment]
https://github.com/TomasVotruba/tomasvotruba.cz/commit/5a058abef4d977432fc7f5b3786102c1640ffea9

Thanks for letting me know, it was confusing

**Comment by B-Galati** [comment]
Great article thank you!

**Comment by TomasVotruba** [comment]
Thanks! 

I suppose you too make open-source :)
What do you find most useful? Do you have some tips to add yourself?

**Comment by B-Galati** [comment]
A little bit yes :-)

>Fail fast to learn fast what works best for your own situation.

Nothing to add!

**Pull request closed without merging**
