### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by freiondrej**
In the sentence "It might be a small deal for performance, but even bigger for legacy code smell that would just me back" there's apparently a verb missing, but I didn't figure out what you meant so I supplied none.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :clap:  nice job

I've added the verb and fixed one more typo

**Comment by freiondrej** [comment]
@TomasVotruba thank you for an interesting article :)

**Comment by TomasVotruba** [comment]
Glad you like it. It feels very exciting to me to write about my mistakes.

What part do you find most useful?

**Comment by TomasVotruba** [comment]
That's great feedback for me! 
I tried to use DI container partially and it got messed, that was the message of the post :) 

> From now on, I'll be trying to take advantage of DI more than ever slightly_smiling_face

What are these cases, where you don't use DI container?

> I like your blog posts, as I can gain experience from your code without having to write it myself +1

Thanks, man, I'm very happy to read these lines

**Comment by freiondrej** [comment]
> What are these cases, where you don't use DI container?

Mostly factories with none or few dependencies - in such case I found it more comfortable to just instantiate locally to "spare" the registration in the container. But after reading your article, I'll inject even these cases :)

Looking forward to reading your future articles ;)

**Comment by TomasVotruba** [comment]
I see. I recommend measuring the performance difference, if that's what you're afraid of.

It will be more fun knowing you're there, thanks.

Btw, if you have some ideas what should I write about or what topics I have in mind, just check issues here and feel free to create one.

**Comment by freiondrej** [comment]
@TomasVotruba thanks - would you mind sharing what do you use for profiling? Sth like Blackfire.io / xdebug profiler / sth else? :)

**Comment by TomasVotruba** [comment]
Blackfire or rather `for ()` cycles with 10 runs :)

**Comment by freiondrej** [comment]
@TomasVotruba thx :) I see that you use `++$i` instead of `$i++` - is it for performance reasons or just a personal preference?

**Comment by TomasVotruba** [comment]
Personal prefference of consistency. I see that value is same before and after use.

Rather than "use it and than change it"

**Comment by freiondrej** [comment]
@TomasVotruba wow, that never occurred to me :) thanks!

**Pull request merged**
