### PR TITLE
[post] add changelog linker post

### PR DESCRIPTION
**Pull request by TomasVotruba**
## Preview

oujee

### CODE REVIEW

**Comment by TomasVotruba** [comment]
@Lexinek Could I ask you for a review before I get to you? :D

**Comment by Lexinek** [comment]
👍

**Comment by TomasVotruba** [comment]
@Lexinek That was fast :zap: You can be more detailed :P

**Comment by Lexinek** [comment]
Article seems fine. 

Does the tool have covered expanding already expanded text etc `#560` vs `[#560](xxxx)`? Im thinking about when running changelog-linker multiple times on same file could lead to unintended bugs.

**Comment by Lexinek** [comment]
Usage is simply stupid 😄 i like that 👍 though there are many Windows os users that are unable to run bash scripts, what about mentioning how can they run it?

**Comment by Lexinek** [comment]
And one offtopic, related to article, my opinion is that too much informations and distractions in changelog (basically in any text) can lead into spending toooo much time in the article 😸

**Comment by TomasVotruba** [comment]
@Lexinek Ad Windows, I guess they know how to do that. I think `./php some-php-script` will do the work.

> And one offtopic, related to article, my opinion is that too much informations and distractions in changelog (basically in any text) can lead into spending toooo much time in the article :smile_cat:

That's why they're not in changelog but in 1 click away ;) 
Also my ambition is not to cure all from age of distraction :D  That's job of [deep work and Cal Newport](https://www.tomasvotruba.cz/blog/2017/09/25/3-non-it-books-that-help-you-to-become-better-programmer/#deep-work-by-cal-newport) (very good at it :+1: )

**Comment by TomasVotruba** [comment]
> @Lexinek Does the tool have covered expanding already expanded text etc #560 vs [#560](xxxx)? Im thinking about when running changelog-linker multiple times on same file could lead to unintended bugs.

Of course :+1:

**Comment by TomasVotruba** [comment]
Thank you :+1: 
 I might add "Honza agrees" note :D

**Comment by Lexinek** [comment]
Yes, i approve 😄 👍

**Pull request merged**
